Ported to Linux
- Removed FreeBSD version check
- Manipulations of zpool.cache were changed from /boot/zfs/zpool.cache
  to /etc/zfs/zpool.cache
- Removed adjustments to loader.conf and loader.conf.local
- Changed path of config file from /usr/local/etc/beadm.conf to /etc/beadm.conf
- Changed to GNU date command
- When activating a dataset, set mountpoint to legacy rather than "/"
- Adjusted beadm mount command to return temporary mount path for use
with scripting
- Added some testing and porting details to README.md

diff --git a/beadm b/beadm
--- a/beadm
+++ b/beadm
@@ -25,15 +25,17 @@
 # (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 # THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+# 2014/12/04 - Ported to Linux - Andrew Barnes (b333z)
+
 unset LC_ALL
 unset LANG
 PATH=${PATH}:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin
 
-if [ $( uname -r | cut -d '-' -f1 | cut -d '.' -f1 ) -lt 8 ]
-then
-  echo "ERROR: beadm works on FreeBSD 8.0 or later"
-  exit 1
-fi
+#if [ $( uname -r | cut -d '-' -f1 | cut -d '.' -f1 ) -lt 8 ]
+#then
+#  echo "ERROR: beadm works on FreeBSD 8.0 or later"
+#  exit 1
+#fi
 
 if [ "${1}" = "--version" -o "${1}" = "version" ]
 then
@@ -197,9 +199,9 @@ then
  exit 1
 fi
 
-if [ -f /usr/local/etc/beadm.conf ]
+if [ -f /etc/beadm.conf ]
 then
-  . /usr/local/etc/beadm.conf
+  . /etc/beadm.conf
 fi
 
 # update GRUB bootloader instead of FreeBSD's loader(8)
@@ -251,12 +253,12 @@ case ${1} in
         return sprintf("%.1f%s", VALUE, UNIT)
       }
       function __get_bename(BENAME) {
-        sub(BENAME_BEGINS_WITH "\/", "", BENAME)
+        sub(BENAME_BEGINS_WITH "/", "", BENAME)
         sub("/.*", "", BENAME)
         return BENAME
       }
       function __convert_date(DATE) {
-        CMD_DATE = "date -j -f \"%a %b %d %H:%M %Y\" \"" DATE "\" +\"%Y-%m-%d %H:%M\""
+        CMD_DATE = "date --date=\"" DATE "\" +\"%Y-%m-%d %H:%M\""
         CMD_DATE | getline NEW
         close(CMD_DATE)
         return NEW
@@ -276,15 +278,18 @@ case ${1} in
           FSNAME_LENGTH = 19
         CMD_MOUNT="mount"
         while(CMD_MOUNT | getline)
-          if($1 ~ "^" BENAME_BEGINS_WITH)
-            MOUNTS[$1] = $3
+          if($1 ~ "^" BENAME_BEGINS_WITH) {
+            if (!($1 in MOUNTS))
+              MOUNTS[$1] = $3
+          }
         close(CMD_MOUNT)
         FS = "\\t"
+        FSNAMESC = 0
         CMD_ZFS_LIST = "zfs list -H -t all -s creation -o name,used,usedds,usedbysnapshots,usedrefreserv,refer,creation,origin -r "
         while(CMD_ZFS_LIST BENAME_BEGINS_WITH | getline) {
           if($1 != BENAME_BEGINS_WITH) {
             FSNAME = $1
-            FSNAMES[length(FSNAMES) + 1] = FSNAME
+            FSNAMES[FSNAMESC++] = FSNAME
             USED              = __normalize($2)
             USEDBYDATASET     = __normalize($3)
             USEDBYSNAPSHOTS   = __normalize($4)
@@ -334,12 +339,14 @@ case ${1} in
         }
         if(OPTION_s != 1)
           SNAPSHOT_FILTER = "(/[^@]*)?$"
-        for(I = 1; I <= length(BENAMES); I++) {
+        BENAMESC = length(BENAMES)
+        for(I = 1; I <= BENAMESC; I++) {
           BENAME = BENAMES[I]
           if(OPTION_a == 1) {
             printf "\n"
             print BENAME
-            for(J = 1; J <= length(FSNAMES); J++) {
+            FSNAMESC = length(FSNAMES)
+            for(J = 1; J <= FSNAMESC; J++) {
               FSNAME = FSNAMES[J]
               if(FSNAME ~ "^" BENAME_BEGINS_WITH "/" BENAME SNAPSHOT_FILTER) {
                 ACTIVE = ""
@@ -376,7 +383,8 @@ case ${1} in
               ACTIVE = ACTIVE "R"
             if(! ACTIVE)
               ACTIVE = "-"
-            for(J = 1; J <= length(FSNAMES); J++) {
+            FNAMESC = length(FSNAMES)
+            for(J = 1; J <= FSNAMESC; J++) {
               FSNAME = FSNAMES[J]
               if(FSNAME ~ "^" BENAME_BEGINS_WITH "/" BENAME "(/[^@]*)?$") {
                 if((BENAME_BEGINS_WITH "/" BENAME) == FSNAME) {
@@ -475,7 +483,7 @@ case ${1} in
       # do not change root (/) mounted boot environment mountpoint
       if [ "${ROOTFS}" != "${POOL}/${BEDS}/${2}" ]
       then
-        TMPMNT=$( mktemp -d -t BE-${2} )
+        TMPMNT=$( mktemp -d -t BE-${2}.XXX )
         if ! mkdir -p ${TMPMNT} 2> /dev/null
         then
           echo "ERROR: Cannot create '${TMPMNT}' directory"
@@ -490,7 +498,7 @@ case ${1} in
             break
           fi
         done << EOF
-$( mount -p )
+$( cat /proc/mounts )
 EOF
         if [ ${MOUNT} -eq 0 ]
         then
@@ -500,22 +508,22 @@ EOF
         else
           TMPMNT=${MOUNT}
         fi
-        if [ -f /boot/zfs/zpool.cache ]
+        if [ -f /etc/zfs/zpool.cache ]
         then
-          cp /boot/zfs/zpool.cache ${TMPMNT}/boot/zfs/zpool.cache
+          cp /etc/zfs/zpool.cache ${TMPMNT}/etc/zfs/zpool.cache
         else
-          rm -f ${TMPMNT}/boot/zfs/zpool.cache
+          rm -f ${TMPMNT}/etc/zfs/zpool.cache
         fi
-        LOADER_CONFIGS=${TMPMNT}/boot/loader.conf
-        if [ -f ${TMPMNT}/boot/loader.conf.local ]
-        then
-          LOADER_CONFIGS="${LOADER_CONFIGS} ${TMPMNT}/boot/loader.conf.local"
-        fi
-        sed -i '' -E s/"^vfs.root.mountfrom=.*$"/"vfs.root.mountfrom=\"zfs:${POOL}\/${BEDS}\/${2##*/}\""/g ${LOADER_CONFIGS}
+        #LOADER_CONFIGS=${TMPMNT}/boot/loader.conf
+        #if [ -f ${TMPMNT}/boot/loader.conf.local ]
+        #then
+        #  LOADER_CONFIGS="${LOADER_CONFIGS} ${TMPMNT}/boot/loader.conf.local"
+        #fi
+        #sed -i '' -E s/"^vfs.root.mountfrom=.*$"/"vfs.root.mountfrom=\"zfs:${POOL}\/${BEDS}\/${2##*/}\""/g ${LOADER_CONFIGS}
         if [ ${MOUNT} -eq 0 ]
         then
           zfs umount ${POOL}/${BEDS}/${2}
-          zfs set mountpoint=/ ${POOL}/${BEDS}/${2}
+          zfs set mountpoint=legacy ${POOL}/${BEDS}/${2}
         fi
       fi
       if ! zpool set bootfs=${POOL}/${BEDS}/${2} ${POOL} 1> /dev/null 2> /dev/null
@@ -540,7 +548,7 @@ EOF
       | grep -E "^${POOL}/${BEDS}/${2}(/|$)" \
       | while read NAME
         do
-          zfs set canmount=on ${NAME}
+          #zfs set canmount=on ${NAME}
           while __be_clone ${NAME}
           do
             zfs promote ${NAME}
@@ -613,7 +621,7 @@ EOF
           # check if boot environment was created from existing snapshot
           ORIGIN=$( zfs list -H -o origin ${POOL}/${BEDS}/${DESTROY} )
           CREATION=$( zfs list -H -o creation ${POOL}/${BEDS}/${DESTROY} )
-          CREATION=$( date -j -f "%a %b %d %H:%M %Y" "${CREATION}" +"%Y-%m-%d-%H:%M" )
+          CREATION=$( date --date="${CREATION}" +"%Y-%m-%d-%H:%M" )
           SNAPSHOT_NAME=$( echo "${ORIGIN}" | cut -d '@' -f 2 | sed -E 's/:[0-9]{2}$//g' )
           if [ "${2}" = "-F" ]
           then
@@ -712,7 +720,7 @@ EOF
   (mount) # ------------------------------------------------------------
     if [ ${#} -eq 2 ]
     then
-      TARGET=$( mktemp -d -t BE-${2} )
+      TARGET=$( mktemp -d -t BE-${2}.XXX )
     elif [ ${#} -eq 3 ]
     then
       TARGET=${3}
@@ -723,7 +731,7 @@ EOF
     if __be_mounted "${POOL}/${BEDS}/${2}"
     then
       MNT=$( mount | grep -E "^${POOL}/${BEDS}/${2} " | awk '{print $3}' )
-      echo "Boot environment '${2}' is already mounted at '${MNT}'"
+      echo "${MNT}"
       exit 1
     fi
     if ! mkdir -p ${TARGET} 2> /dev/null
@@ -768,7 +776,7 @@ EOF
             exit 1
           fi
         done
-    echo "Mounted successfully on '${TARGET}'"
+    echo "${TARGET}"
     ;;
 
   (umount|unmount) # ----------------------------------------------------------
